name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  # https://python-semantic-release.readthedocs.io/en/stable/automatic-releases/github-actions.html
  release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
